import { GetStoreList } from './type';

export const mockStoreListResponse: GetStoreList = {
  status: 'OK',
  data: [
    {
      id: 1,
      ownerId: 1,
      name: '홍가네',
      regionId: 'KR-11',
      city: '홍대',
      address: '서울특별시 마포구',
      category: '한식',
      description: '설명설명',
      priceCategory: '15000 ~ 30000',
      eventDescription: '이벤트없음',
      contactNumber: '010-0000-0000',
      direction: '홍대입구역 2번출구 앞',
      information: '오전9시 ~ 오후9시',
      latitude: 36.40947226931638,
      longitude: 127.12345678901234,
      visitCount: 1000,
      reviewCount: 246,
      bookmarkCount: 100,
      stations: [{id: 1, name: '개봉역', line: '3호선', address: '서울특별시 개봉동'}],
      parkingAvailable: true,
      newOpen: true,
      takeOut: true,
      isParkingAvailable: true,
      isNewOpen: true,
      isTakeOut: true,
    },
    {
      id: 2,
      ownerId: 1,
      name: '민서네 김밥 홍대점',
      regionId: 'KR-11',
      city: '홍대',
      address: '서울특별시 마포구',
      category: '분식',
      description: '김밥과 떡볶이가 맛있는 집',
      priceCategory: '5000 ~ 10000',
      eventDescription: '오전 11시 이전 방문 시 커피 무료',
      contactNumber: '02-123-4567',
      direction: '홍대입구역 3번출구 100m 직진',
      information: '오전8시 ~ 오후8시',
      latitude: 37.5585,
      longitude: 126.925,
      visitCount: 500,
      reviewCount: 120,
      bookmarkCount: 55,
      stations: [{id: 1, name: '개봉역', line: '3호선', address: '서울특별시 개봉동'}],

      parkingAvailable: false,
      newOpen: false,
      takeOut: true,
      isParkingAvailable: false,
      isNewOpen: false,
      isTakeOut: true,
    },
  ],
};
