import { GetStoreByIdResponse, GetStoreListResponse } from './type';

export const mockStoreListResponse: GetStoreListResponse = {
  status: 'OK',
  data: {
    pageInfo: {
      pageNum: 1,
      pageSize: 10,
      totalPages: 1,
      totalCount: 3,
    },
    list: [
      {
        id: 1,
        name: '바다풍경 정육식당 흑돼지 용담탑동본점',
        mainImage: null,
        averageRating: 4.9,
        city: '합정',
        estimatedWaitingTimeMinutes: 20,
        visitCount: 1000,
        reviewCount: 231,
        isBookMarded: false,
        isFinished: false,
      },
      {
        id: 2,
        name: '엉터리 생고기 엉생 무한리필 아산테크노본점',
        mainImage: null,
        averageRating: 4.9,
        city: '합정',
        estimatedWaitingTimeMinutes: 20,
        visitCount: 1000,
        reviewCount: 231,
        isBookMarded: false,
        isFinished: false,
      },
      {
        id: 3,
        name: '민서네 김밥 홍대점',
        mainImage: null,
        averageRating: 4.9,
        city: '합정',
        estimatedWaitingTimeMinutes: 20,
        visitCount: 1000,
        reviewCount: 231,
        isBookMarded: false,
        isFinished: false,
      },
      {
        id: 4,
        name: '민서네 김밥 홍대점',
        mainImage: null,
        averageRating: 4.9,
        city: '합정',
        estimatedWaitingTimeMinutes: 20,
        visitCount: 1000,
        reviewCount: 231,
        isBookMarded: false,
        isFinished: false,
      },
      {
        id: 5,
        name: '민서네 김밥 홍대점',
        mainImage: null,
        averageRating: 4.9,
        city: '합정',
        estimatedWaitingTimeMinutes: 20,
        visitCount: 1000,
        reviewCount: 231,
        isBookMarded: false,
        isFinished: false,
      },
    ],
  },
};

export const mockStoreByIdResponse: GetStoreByIdResponse = {
  status: 'OK',
  data: {
    id: 1,
    name: '홍길동 식당',
    mainImage: null,
    city: '합정',
    address: '서울특별시 마포구',
    category: '한식',
    description: '설명설명',
    priceCategory: '15000 ~ 30000',
    eventDescription: '이벤트없음',
    contactNumber: '010-0000-0000',
    direction: '홍대입구역 2번출구 앞',
    visitCount: 1000,
    reviewCount: 246,
    averageRating: 4.5,
    isParkingAvailable: true,
    isNewOpen: true,
    isTakeOut: true,
    estimatedWaitingTimeMinutes: 20,
  },
};
