import { GetBookmarkStoreListResponse } from './type';

export const mockBookmarkStoreListResponse: GetBookmarkStoreListResponse = {
  status: 'OK',
  data: {
    pageInfo: {
      pageNum: 1,
      pageSize: 10,
      totalPages: 1,
      totalCount: 4,
    },
    list: [
      {
        id: 1,
        storeId: 1,
        name: '바다풍경 정육식당 흑돼지 용담탑동본점',
        images: [],
        averageRating: 4.9,
        estimatedWaitingTimeMinutes: 20,
        visitCount: 1000,
        reviewCount: 231,
        isFinished: false,
        bookmarkCount: 10,
      },
      {
        id: 2,
        name: '엉터리 생고기 엉생 무한리필 아산테크노본점',
        storeId: 2,
        images: [],
        averageRating: 4.9,
        estimatedWaitingTimeMinutes: 20,
        visitCount: 1000,
        reviewCount: 231,
        isFinished: false,
        bookmarkCount: 10,
      },
      {
        id: 3,
        name: '민서네 김밥 홍대점',
        storeId: 3,
        images: [],
        averageRating: 4.9,
        estimatedWaitingTimeMinutes: 20,
        visitCount: 1000,
        reviewCount: 231,
        isFinished: false,
        bookmarkCount: 0,
      },
      {
        id: 4,
        name: '민서네 김밥 홍대점',
        storeId: 4,
        images: [],
        averageRating: 4.9,
        estimatedWaitingTimeMinutes: 20,
        visitCount: 1000,
        reviewCount: 231,
        bookmarkCount: 0,
        isFinished: false,
      },
      {
        id: 5,
        name: '민서네 김밥 홍대점',
        images: [],
        averageRating: 4.9,
        estimatedWaitingTimeMinutes: 20,
        visitCount: 1000,
        reviewCount: 231,
        isFinished: false,
        bookmarkCount: 0,
        storeId: 5,
      },
    ],
  },
};
