import { GetBookmarkStoreListResponse, GetUserRewardLogResponse } from './type';

export const mockBookmarkStoreListResponse: GetBookmarkStoreListResponse = {
  status: 'OK',
  data: {
    pageInfo: {
      pageNum: 1,
      pageSize: 10,
      totalPages: 1,
      totalCount: 4,
    },
    list: [
      {
        id: 1,
        storeId: 1,
        name: '바다풍경 정육식당 흑돼지 용담탑동본점',
        images: [],
        averageRating: 4.9,
        city: '제주 제주시 서해안로 654',
        estimatedWaitingTimeMinutes: 20,
        visitCount: 1000,
        reviewCount: 231,
        isFinished: false,
        bookmarkCount: 10,
      },
      {
        id: 2,
        name: '엉터리 생고기 엉생 무한리필 아산테크노본점',
        storeId: 2,
        images: [],
        averageRating: 4.9,
        city: '합정',
        estimatedWaitingTimeMinutes: 20,
        visitCount: 1000,
        reviewCount: 231,
        isFinished: false,
        bookmarkCount: 10,
      },
      {
        id: 3,
        name: '민서네 김밥 홍대점',
        storeId: 3,
        images: [],
        averageRating: 4.9,
        city: '합정',
        estimatedWaitingTimeMinutes: 20,
        visitCount: 1000,
        reviewCount: 231,
        isFinished: false,
        bookmarkCount: 0,
      },
      {
        id: 4,
        name: '민서네 김밥 홍대점',
        storeId: 4,
        images: [],
        averageRating: 4.9,
        city: '합정',
        estimatedWaitingTimeMinutes: 20,
        visitCount: 1000,
        reviewCount: 231,
        bookmarkCount: 0,
        isFinished: false,
      },
      {
        id: 5,
        name: '민서네 김밥 홍대점',
        images: [],
        averageRating: 4.9,
        city: '합정',
        estimatedWaitingTimeMinutes: 20,
        visitCount: 1000,
        reviewCount: 231,
        isFinished: false,
        bookmarkCount: 0,
        storeId: 5,
      },
    ],
  },
};

export const mockUserRewardLogResponse: GetUserRewardLogResponse = {
  status: 'OK',
  data: {
    pageInfo: {
      pageNum: 1,
      pageSize: 10,
      totalPages: 1,
      totalCount: 7,
    },
    list: [
      {
        id: 1,
        storeName: '강샤브샤브',
        storeId: 5,
        point: 10,
        avaliablePoint: 10,
        used: false,
        type: 'VISIT',
        createdAt: '2025-08-20T03:44:25.499Z',
      },
      {
        id: 2,
        storeName: '강샤브샤브',
        storeId: 5,
        point: 20,
        avaliablePoint: 30,
        used: false,
        type: 'VISIT',
        createdAt: '2025-08-19T03:44:25.499Z',
      },
      {
        id: 3,
        storeName: '강샤브샤브',
        storeId: 5,
        point: 20,
        avaliablePoint: 50,
        used: false,
        type: 'VISIT',
        createdAt: '2025-05-20T07:44:25.499Z',
      },
      {
        id: 4,
        storeName: '강샤브샤브',
        storeId: 5,
        point: 10,
        avaliablePoint: 40,
        used: true,
        type: 'VISIT',
        createdAt: '2025-05-03T10:44:25.499Z',
      },
      {
        id: 5,
        storeName: '798화로 홍대본점',
        storeId: 26,
        point: 10,
        avaliablePoint: 40,
        used: true,
        type: 'VISIT',
        createdAt: '2025-04-10T10:44:25.499Z',
      },
      {
        id: 6,
        storeName: '798화로 홍대본점',
        storeId: 26,
        point: 20,
        avaliablePoint: 50,
        used: false,
        type: 'VISIT',
        createdAt: '2025-03-27T06:44:25.499Z',
      },
      {
        id: 7,
        storeName: '798화로 홍대본점',
        storeId: 26,
        point: 10,
        avaliablePoint: 30,
        used: true,
        type: 'VISIT',
        createdAt: '2025-03-21T02:44:25.499Z',
      },
    ],
  },
};

//TODO: 추후 수정

export const mockUserRewardDetailResponse = {
  status: 'OK',
  data: {
    id: 7,
    storeName: '798화로 홍대본점',
    storeId: 26,
    point: 10,
    avaliablePoint: 30,
    used: true,
    type: 'VISIT',
    createdAt: '2025-03-21T02:44:25.499Z',
  },
};
