name: design-system-develop-CI

on:
  push:
    branches: [develop]
    tags: [design-system**]
    paths:
      - 'packages/design-system/**'
      - '_config/**'
      - '_package/**'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.BUILD_SLACK_WEBHOOK_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./packages/design-system/Dockerfile
          push: true
          tags: hyperrealitycorp/fooding-design-system-stage
          platforms: linux/amd64, linux/arm64/v8
          build-args: |
            COMMIT_HASH=${{ github.sha }}
      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGE_REMOTE_SSH_IP }}
          username: ${{ secrets.STAGE_REMOTE_SSH_ID }}
          password: ${{ secrets.STAGE_REMOTE_SSH_PASSWORD }}
          port: ${{ secrets.STAGE_REMOTE_SSH_PORT }}
          script: |
            source ~/.bashrc
            bash ./deployment/fooding/design-system-stage.sh
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#build-status'
        if: always() 